### PR TITLE
Added GOOGLE_API_KEY to readme environment section

### PR DESCRIPTION
**Pull request by DSSzymanski**
README's environment layout was missing information on the key needed to run the Google command.  Added the key to list of environment keys and a link for where to obtain the key.

### CODE REVIEW

**Review by ryuga — CHANGES_REQUESTED** [review]
This merge causes linting errors which are currently fixed, Sync your fork with our dev branch so we can merge this pr.

**Comment by ryuga** [comment]
Also, this pr may not count to your Hacktoberfest contribution since it only changes few lines.
It goes against the spirit of Hacktoberfest. So if you go even as far as implementing a basic feature or adding a misc command we may consider approving it for the hacktoberfest.

**Comment by DSSzymanski** [comment]
Weird, I could've sworn I put this on a different branch, I didn't think syncing to the other update would throw errors on this pull request, my mistake.

I was the one who made the pull request for issue #161. It was just something I noticed was missing when I was trying to troubleshoot the google command and had meant to add it to that commit, but it slipped my mind. I wasn't expecting it to count for Hacktoberfest, just something to help the next person that comes along that wants to work on that command.

**Comment by ryuga** [comment]
Fair enough. I forgot about your first PR. Seems like you've synced your fork. I will merge it now. Thank you for the contribution. If you are on discord be sure to checkout our server.

**Pull request merged**
