### PR TITLE
Added more randomness related commands in cogs/misc.py

### PR DESCRIPTION
**Pull request by aryamaanthakur**
I've added 3 new commands in cogs/misc.py for issue #147 

Random: Generates n integers in the given interval
Shuffle: Randomly orders the given sequence of strings
Choice: Selects a random one from the given options

Please review my PR. Thank you!

Example:

image

### CODE REVIEW

**Comment by ryuga** [comment]
Hi there, We really appreciate you're taking the effort to implement commands to the tortoise bot, We are always open to contributions. But your pull requests are just an implementation of the basic python module, there is nothing build on top of it.
While we can still include these commands under misc I would recommend you add a functionality that makes use of these modules like the `blackjack` command we have on the bot. If you don't have any idea for a new functionality you can work on the issues the easiest ones are labeld as `good first issue`.

**Comment by aryamaanthakur** [comment]
I will try my best to do that.

**Comment by aryamaanthakur** [comment]
I tried resolving issue #148
Please review my PR

**Comment by ryuga** [comment]
Thank you for the contribution, The PR passes all checks plus it resolves and issue. Will merge it now.

**Comment by albertopoljak** [comment]
Nah dw all good, I just pulled and it didn't work with spaces which I'm used to when working with *args so made a quick comment but halfway trough I saw it used comma, but I already made changes to work with space.  My bad.

**Pull request merged**
