### PR TITLE
XKCD Module

### PR DESCRIPTION
**Pull request by jdl-joseph**
I will soon write a cog file that goes along with xkcd_helper.py

### CODE REVIEW

**Comment by jdl-joseph** [comment]
check the flake8 lint errors. i think this is able to merge. the errors aren't caused by visible errors in my program.

**Comment by ryuga** [comment]
The branch could be merged without conflicts. But there are quiet a few lint errors as you can see from here,
https://github.com/Tortoise-Community/Tortoise-BOT/runs/4063147461?check_suite_focus=true#step:2:1

**Comment by ryuga** [comment]
See if you can fix it, Just running your code through Pycharm or other IDE will point out the errors or fix them for you,

**Comment by jdl-joseph** [comment]
We can agree on the fact that the (\w) and (\s) are necessary though, right?

**Comment by jdl-joseph** [comment]
also, what does that E501 line too long (145 > 120 characters) thing mean? sorry i haven't much experience with flake lol

**Comment by ryuga** [comment]
> also, what does that E501 line too long (145 > 120 characters) thing mean? sorry i haven't much experience with flake lol

A maximum of 120 characters are allowed per line. Part of your code exceeds that limit.

**Pull request closed without merging**
