### PR TITLE
Fight cog

### PR DESCRIPTION
**Pull request by VoidyCD**
Hopefully it works this time

### CODE REVIEW

**Comment by VoidyCD** [comment]
The error was that there was a return statement in the code that makes it so that people can't play in the same channel, it shouldnt make an error soo yep

**Comment by albertopoljak** [comment]
You're missing some imports and it's failing Flake8, when you solve those I'll look deeper.

**Comment by ryuga** [comment]
We have setup flake8 for the project. 
Once you are done with the code, before making a PR run the script for flake8 `pipenv run lint` on the terminal which will give you a list of all the lint errors that you need to solve. Once you get a 0 returned after the script execution you are all good to make a PR.

**Comment by ryuga** [comment]
The PR looks abandoned. Closing

**Pull request closed without merging**
