### PR TITLE
Fixed NSFW post handling and improved the embed

### PR DESCRIPTION
**Pull request by fwizzz**
With these changes, **The bot will not send any nsfw posts and will show a warning instead.**

**Also I improved the overall looks and info of the reddit embed** 

- Added the subreddits name and icon in the author field
- Added the name and icon of the post author in the footer field
- Added a timestamp that shows when the post was created

### CODE REVIEW

**Comment by albertopoljak** [comment]
Change this to push to dev branch.

**Comment by fwizzz** [comment]
> Change this to push to dev branch.

yo wait how do i do that

**Comment by albertopoljak** [comment]
Currently you've set if from master to master:
`Tortoise-Community:master from fwizzz:master`
normaly it should be from dev to dev:
`Tortoise-Community:dev from fwizzz:dev`
but since you've forked and did commits on master branch in your fork then it should be:
`Tortoise-Community:dev from fwizzz:master`
Note that this might have conflicts since you should have forked and commit all to dev branch.

**Comment by albertopoljak** [comment]
Oke it has come to my attention that this is already merged by the previous PR.
Was confused because I though this was something separate as usually PRs are separate.
So ye this is already merged by #106

**Comment by fwizzz** [comment]
yeah lol thats why i closed it

**Pull request closed without merging**
