### PR TITLE
eightball

### PR DESCRIPTION
**Pull request by jdl-monkey-coder**

### CODE REVIEW

**Comment by jdl-monkey-coder** [comment]
ookay

**Comment by albertopoljak** [comment]
I don't see your commit there, you're only trying to update the master from your dev branch..anyway next time update your repo and push to dev

**Comment by jdl-monkey-coder** [comment]
oke

**Comment by jdl-monkey-coder** [comment]
Soooo make a commit in my repo and then select TortoiseCommunity:dev when at screen that prompts which branch to push to? Sent from Mail for Windows 10 From: BraindeadSent: Monday, January 11, 2021 2:37 PMTo: Tortoise-Community/Tortoise-BOTCc: JDLEE; AuthorSubject: Re: [Tortoise-Community/Tortoise-BOT] eightball (#135) I don't see your commit there, you're only trying to update the master from your dev branch..anyway next time update your repo and push to dev—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com

**Pull request closed without merging**
